-- ASIKO Boutique Migration 07: 3D GLTF Asset Columns
-- Adds model_3d_url to products, mesh metadata to product_variants,
-- and seeds paths to the actual .glb files in static/models/

BEGIN;

-- ============================================================================
-- 1. Add 3D model URL column to products table
-- ============================================================================
ALTER TABLE products
    ADD COLUMN IF NOT EXISTS model_3d_url VARCHAR(512) DEFAULT NULL;

-- ============================================================================
-- 2. Add mesh & shader metadata columns to product_variants table
-- ============================================================================
ALTER TABLE product_variants
    ADD COLUMN IF NOT EXISTS mesh_node_identifier VARCHAR(100) DEFAULT NULL;
ALTER TABLE product_variants
    ADD COLUMN IF NOT EXISTS custom_shader_color VARCHAR(7) DEFAULT NULL;

-- ============================================================================
-- 3. Seed 3D model paths on existing products that have GLB counterparts
--    The GLB files live in static/models/ and were generated by
--    scripts/generate_glb_models.py
-- ============================================================================

-- Lagos Silk Blazer → architectural-blazer.glb (structured shoulder silhouette)
UPDATE products
SET model_3d_url = '/static/models/architectural-blazer.glb'
WHERE name LIKE '%Silk Blazer%' AND model_3d_url IS NULL;

-- Adire Tie-Dye Dress → draped-silhouette-gown.glb (floor-length gown silhouette)
UPDATE products
SET model_3d_url = '/static/models/draped-silhouette-gown.glb'
WHERE name LIKE '%Adire%' AND model_3d_url IS NULL;

-- Atelier Drape Dress (seeded in schema.sql) → draped-silhouette-gown.glb
UPDATE products
SET model_3d_url = '/static/models/draped-silhouette-gown.glb'
WHERE (name LIKE '%Drape Dress%' OR name LIKE '%Draped%')
  AND model_3d_url IS NULL;

-- Aba Handloomed Trousers → tailored-column-trouser.glb (tapered trouser silhouette)
UPDATE products
SET model_3d_url = '/static/models/tailored-column-trouser.glb'
WHERE name LIKE '%Trousers%' AND model_3d_url IS NULL;

-- ============================================================================
-- 4. Seed mesh_node_identifier and custom_shader_color on variants
--    Mesh identifiers match the Three.js GLTFLoader expectations
--    Shader colors match the brand palette
-- ============================================================================

-- Blazer variants → structural blazer mesh, deep forest green
UPDATE product_variants v
SET
    mesh_node_identifier = 'Blazer_Mesh',
    custom_shader_color = CASE
        WHEN v.color LIKE '%Navy%' THEN '#0D2A22'
        WHEN v.color LIKE '%Cream%' OR v.color LIKE '%Ivory%' THEN '#D4AF37'
        ELSE '#0D2A22'
    END
FROM products p
WHERE v.product_id = p.id
  AND p.model_3d_url LIKE '%architectural-blazer%'
  AND v.mesh_node_identifier IS NULL;

-- Dress variants → gown mesh, gold/champagne
UPDATE product_variants v
SET
    mesh_node_identifier = 'Gown_Mesh',
    custom_shader_color = CASE
        WHEN v.color LIKE '%Indigo%' OR v.color LIKE '%Blue%' THEN '#1A1A1A'
        WHEN v.color LIKE '%Brown%' OR v.color LIKE '%Earth%' THEN '#D4AF37'
        WHEN v.color LIKE '%Black%' OR v.color LIKE '%Onyx%' THEN '#0D0D0D'
        ELSE '#D4AF37'
    END
FROM products p
WHERE v.product_id = p.id
  AND p.model_3d_url LIKE '%draped-silhouette-gown%'
  AND v.mesh_node_identifier IS NULL;

-- Trouser variants → trouser mesh, charcoal
UPDATE product_variants v
SET
    mesh_node_identifier = 'Trouser_Mesh',
    custom_shader_color = CASE
        WHEN v.color LIKE '%Grey%' OR v.color LIKE '%Charcoal%' THEN '#4A4A4A'
        WHEN v.color LIKE '%Sand%' OR v.color LIKE '%Khaki%' THEN '#C4A35A'
        ELSE '#4A4A4A'
    END
FROM products p
WHERE v.product_id = p.id
  AND p.model_3d_url LIKE '%tailored-column-trouser%'
  AND v.mesh_node_identifier IS NULL;

-- ============================================================================
-- 5. Fix any schema.sql seed that pointed to wrong/legacy paths
--    Old schema.sql used /static/assets/models/ which doesn't exist
-- ============================================================================
UPDATE products
SET model_3d_url = REPLACE(model_3d_url, '/static/assets/models/', '/static/models/')
WHERE model_3d_url LIKE '/static/assets/models/%';

COMMIT;
